### ISSUE TITLE
Não funciona

### ISSUE THREAD

**Issue by carnivash** [wgenial/consulta-placa-serverless#2]
O único resultado que vem é esse:

{
error: {
code: "ECONNRESET",
errno: "ECONNRESET",
syscall: "read"
}
}

**Comment by giovanigenerali** [comment]
@carnivash É bloqueio na chamada pelo SINESP e tem que passar um proxy via process.env.HTTP_PROXY um que seja do Brasil.

**Comment by giovanigenerali** [comment]
Acabei de publicar uma nova versão com diversas melhorias e explicação sobre o erro informado.
